#!/bin/bash

cmd="${1:-start}"

start_order=(
    sirepo_job_supervisor.service
    sirepo@{7000..7003}.service
    raydata_scan_monitor.service
)

function list() {
    <<<"${start_order[@]}" tr ' ' '\n'
}

function start() {
    list | xargs -tL 1 systemctl start
}

function stop() {
    list | tac | xargs -tL 1 systemctl stop
}

function status() {
    systemctl -n 0 status "${start_order[@]}"
}

function journal() {
    local args=$(list | sed 's/^/-u /')
    journalctl -f $args
}

case "$cmd" in
start)
    start ;;
stop)
    stop ;;
restart)
    stop 
    start ;;
status)
    status ;;
journal)
    journal ;;
*)
    echo "Command '$cmd' unrecognized" ;;
esac

